### ISSUE TITLE
README.md | Contributing | Hyperlink doesn't work

### ISSUE THREAD

**Issue by NajmAjmal** [AnderGoig/github-contributions-ios#16]
Hi @AnderGoig,

When clicking on the [Contributing](https://github.com/AnderGoig/github-contributions-ios#contributing), it redirects to a GitHub 404 page. Perhaps the page is missing, or has been deleted.

Thanks, Najm

**Comment by AnderGoig** [comment]
Hey @NajmAjmal, thanks a lot for reporting this! it should be fixed now 🙇
