### ISSUE TITLE
Feature Request : When click on ContributionsRow, navigate to the GitHub user page.

### ISSUE THREAD

**Issue by hyphen-o** [AnderGoig/github-contributions-ios#19]
**Is your feature request related to a problem? Please describe.**
First of all, thank you very much for developing this wonderful app. Now, let's get to the main point. Currently, there is no click event set for ContributionsRow, but I would like it to be configured so that when clicked, it navigates to the corresponding user's GitHub account page.  I look forward to your response.

**Describe the solution you'd like**
When ContributionsRow is clicked, navigate to the GitHub account page of the corresponding user.

**Comment by AnderGoig** [comment]
Hey @hyphen-o, thanks for your suggestion! That's actually a great idea and should be quite easy to implement, will see if I can prepare something.

**Comment by AnderGoig** [comment]
This is now implemented 0b874bbe278db4df2c1bda0d47f9c8d0cccff60d, it will be available in future releases 🎉

**Comment by k1tikurisu** [comment]
YAAAAAS!🥳

**Comment by hyphen-o** [comment]
thank you!!🥰🥰
