### ISSUE TITLE
Set a Github username bug

### ISSUE THREAD

**Issue by mjlee111** [AnderGoig/github-contributions-ios#26]
**Describe the bug**
on IOS 17.6.1 even if I had set the user name, contributions won't show up.

**Screenshots**
![KakaoTalk_20241014_025835107](https://github.com/user-attachments/assets/7d7be6d4-9702-48d3-8028-cab3a7699305)

![KakaoTalk_20241014_025835107_01](https://github.com/user-attachments/assets/34641967-0934-4e4d-8eff-4a6f05dd5cd8)

**Smartphone (please complete the following information):**
 - Device: iphone 15
 - OS: ios 17.6.1
 - Version: 1.4.6(16)

**Comment by AnderGoig** [comment]
Hi @mjlee111,

It doesn't work like that, app's usernames are separated from the widget usernames. You'd need to edit the widget by holding it, tapping it and then setting your username within the widget settings.

There's a guide inside the app at **Settings > Widget Setup**, so you can have a look at it if needed.

Hope that helps!

**Comment by mjlee111** [comment]
Thank you for your kindness :)
