### ISSUE TITLE
Spanish widget when chose English

### ISSUE THREAD

**Issue by jeremmfr** [AnderGoig/github-contributions-ios#3]
**Describe the bug**
If chose English in parameters, application switch in English but widget stay in Spanish 'Contributionnes' and widget options 'Usuario', 'Tema' ...

**To Reproduce**
1. Install app
2. It's in Spanish by default. Switch in English in parameters.
3. Add widget with medium size on home.
4. See widget with Spanish word for contribution
5. Open widget options and see Spanish words for username, colors, ...

**Expected behavior**
English words in widget when chose English in parameters 

**Smartphone :**
 - Device: iPhone12
 - OS: iOS14.1
 - Version: 1.0.2 (4)

**Comment by AnderGoig** [comment]
Thanks @jeremmfr! I will take a look to see if I can reproduce it.

**Comment by jeremmfr** [comment]
Thanks.  
A precision. Global language parameter in my device is French.  
I tested application with XCode Simulator. Global language parameter in simulator is English, so application default language is English. If switch application parameter in Spanish, application words is in Spanish but widget stay in English. This is same bug as my first explanation.

**Comment by jeremmfr** [comment]
We can close this issue, it's general to all iOS widgets which do not respect the choice of the language on the application but choose the first available language in the default list of the system.
