### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by FMS187** [AnderGoig/github-contributions-ios#4]
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS14.1]
 - Version: [e.g. 1.0.0 (22)]

**Additional context**

**Comment by AnderGoig** [comment]
@FMS187 Did you open this issue by mistake? I see no information whatsoever apart from the title 🤔
