### ISSUE TITLE
An error occurred while fetching contributions from GitHub.

### ISSUE THREAD

**Issue by riceset** [AnderGoig/github-contributions-ios#7]
![image](https://user-images.githubusercontent.com/48802655/102409199-688f4f00-3fcd-11eb-97fb-67c0c5c23826.jpeg)
Every time I restart my phone, this message appears. I have to delete the widget, add it again and change its color for it start working again.

iPhone XR
IOS 14.3

**Comment by AnderGoig** [comment]
I uploaded a new build yesterday to fix that, it will be hopefully available soon in the App Store 🤞

**Comment by AnderGoig** [comment]
Issue solved in [1.1.0](https://github.com/AnderGoig/github-contributions-ios/releases/tag/1.1.0), update to fix it!
