### ISSUE TITLE
OLED mode

### ISSUE THREAD

**Issue by bradystroud** [AnderGoig/github-contributions-ios#9]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I think a proper black widget would look really good on OLED

**Additional context**
![image](https://user-images.githubusercontent.com/38869720/106131337-4aad3080-61ae-11eb-9872-40f1794fd13f.jpeg)
This is what it currently looks like on my black wallpaper

![image](https://user-images.githubusercontent.com/38869720/106131414-61538780-61ae-11eb-860c-8aa4ba0c6731.jpeg)
I want it to look like these widgets.

**Comment by AnderGoig** [comment]
Thanks @bradystroud, I like the idea! Will think about adding it as an option.

**Comment by AnderGoig** [comment]
Hey @bradystroud, you can now enable the option **Pure Black Background** inside the widget options in **1.1.0**, closing this one!
